# Site settings
title: Sass break - A simple blog about Sass
email: g.hernandez07@gmail.com
description: "A simple blog about Sass."
baseurl: ""
url: "http://sassbreak.com"
twitter_username: sassbreak
github_username:  jekyll
relative_path: /
highlighter: pygments

# Build settings
markdown: kramdown
permalink: pretty
