# Site settings
title: Sass break - A Sass blog
email: g.hernandez07@gmail.com
description: "A simple blog about Sass."
baseurl: ""
url: "http://sassbreak.com"
twitter_username: sassbreak
github_username:  jekyll
relative_path: /
# highlighter: pygments
paginate: 6

#gems
gems: [jekyll-paginate, jekyll-gist]

# Build settings
markdown: kramdown
permalink: pretty
